# Krótkie wprowadzenie do numpy

Importujemy bibliotekę **numpy**.
Dla ułatwienia korzystamy ze skróconej nazwy **np**.

In [79]:
import numpy as np

## Szukanie maksimum

Tworzymy tablicę 5x4 wypełnioną wartościami od 0 do 19.

In [80]:
array = np.arange(20).reshape(5, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Szukamy indeksu maksimum w tablicy. Domyślnie znajdujemy indeks maksimum w całej tablicy.

In [81]:
print(np.argmax(array))

19


Jeżeli podamy parametr axis=1, to znajdziemy indeks maksimum dla każdego wiersza.

In [82]:
print(np.argmax(array, axis=1))

[3 3 3 3 3]


Jeżeli podamy parametr axis=1, to znajdziemy indeks maksimum dla każdej kolumny.

In [83]:
print(np.argmax(array, axis=0))

[4 4 4 4]


## Sortowanie

Tworzymy przykładową tablicę

In [84]:
array = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])
print(array)

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]


Sortujemy całą tablicę.

In [85]:
print(np.sort(array, axis=None))

[ 1  2  3  3  5  6  7  7 10]


Sortujemy wiersze.

In [86]:
print(np.sort(array, axis=1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


Sortujemy kolumny.

In [87]:
print(np.sort(array, axis=0))

[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


## Szukamy mediany

Tworzymy listę tablic numpy.

In [88]:
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

Dla każdej tablicy obliczamy medianę.

In [89]:
result = []
for i in range(len(list)):
    result.append(np.mean(list[i]))
print(result)

[5.5, 30.6, 34.0]


## Dodawanie wierzy i kolumn

Tworzymy przykładową tablicę numpy.

In [90]:
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])
print(array)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]]


Tworzymy nowy wiersz.

In [91]:
newRow = np.array([2, 1, 8])
print(newRow)

[2 1 8]


Tworzymy nową tablicę z dodanym wierszem.

In [92]:
newArray = np.vstack((array, newRow))
print(newArray)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


Tworzymy nową kolumnę.

In [93]:
newColumn = np.array([2, 1, 8])
print(newColumn)

[2 1 8]


Tworzymy nową tablicę z dodaną kolumną.

In [94]:
newArray = np.column_stack((array, newColumn))
print(newArray)

[[ 3  2  8  2]
 [ 4 12 34  1]
 [23 12 67  8]]


## Odwracanie tablicy

Tworzymy nową tablicę numpy.

In [95]:
array = np.array([3, 6, 7, 2, 5, 1, 8])

Tworzymy odwróconą tablicę.

In [96]:
reversedArray = np.flipud(array)
print(reversedArray)

[8 1 5 2 7 6 3]


## Mnożenie macierzy

Tworzymy macierze.

In [97]:
matrix1 = np.array([
    [3, 4, 2],
    [5, 1, 8],
    [3, 1, 9]
])
print(matrix1)

[[3 4 2]
 [5 1 8]
 [3 1 9]]


In [98]:
matrix2 = np.array([
    [3, 7, 5],
    [2, 9, 8],
    [1, 5, 8]
])
print(matrix2)

[[3 7 5]
 [2 9 8]
 [1 5 8]]


Obliczamy ich iloczyn.

In [99]:
result = np.dot(matrix1, matrix2)
print(result)

[[19 67 63]
 [25 84 97]
 [20 75 95]]


## Wzór szachownicy

Definiujemy rozmiar szachownicy.

In [100]:
n = 8

Tworzymy macierz n x n wypełnioną zerami.

In [101]:
matrix = np.zeros((n, n), dtype=int)

Wypełniamy jedynkami naprzemienne wiersze i kolumny

In [102]:
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
