# Krótkie wprowadzenie do numpy

Importujemy bibliotekę **numpy**.
Dla ułatwienia korzystamy ze skróconej nazwy **np**.

In [61]:
import numpy as np

## Szukanie maksimum

Tworzymy tablicę 5x4 wypełnioną wartościami od 0 do 19.

In [62]:
array = np.arange(20).reshape(5, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Szukamy indeksu maksimum w tablicy. Domyślnie znajdujemy indeks maksimum w całej tablicy.

In [63]:
print(np.argmax(array))

19


Jeżeli podamy parametr axis=1, to znajdziemy indeks maksimum dla każdego wiersza.

In [64]:
print(np.argmax(array, axis=1))

[3 3 3 3 3]


Jeżeli podamy parametr axis=1, to znajdziemy indeks maksimum dla każdej kolumny.

In [65]:
print(np.argmax(array, axis=0))

[4 4 4 4]


## Sortowanie

Tworzymy przykładową tablicę

In [66]:
array = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])
print(array)

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]


Sortujemy całą tablicę.

In [67]:
print(np.sort(array, axis=None))

[ 1  2  3  3  5  6  7  7 10]


Sortujemy wiersze.

In [68]:
print(np.sort(array, axis=1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


Sortujemy kolumny.

In [69]:
print(np.sort(array, axis=0))

[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


## Szukamy mediany

Tworzymy listę tablic numpy.

In [70]:
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

Dla każdej tablicy obliczamy medianę.

In [71]:
result = []
for i in range(len(list)):
    result.append(np.mean(list[i]))
print(result)

[5.5, 30.6, 34.0]
