# Krótkie wprowadzenie do numpy

Biblioteka numpy przydaje się do wykonywania wielu obliczeń w pythonie, w szczególności obliczeń na listach i macierzach.

Dla przykładu: chcemy obliczyć iloczyn dwóch tablic zawierających liczby całkowite.

In [224]:
list1 = [2, 4, 6, 7, 8]
list2 = [3, 4, 6, 1, 5]

# print(list1*list2)

Taka operacja zakończy się błędem. Wykorzystując jednak bibliotekę numpy możemy to łatwo zrobić.

Najpierw musimy ją zainstalować poleceniem

``
pip install numpy
``

Następnie importujemy bibliotekę **numpy**.
Dla ułatwienia korzystamy ze skróconej nazwy **np**.

In [225]:
import numpy as np

Tweraz możemy utworzyć dwie tablice numpy i je przemnożyć.

In [226]:
arr1 = np.array(list1)
arr2 = np.array(list2)

print(arr1*arr2)

[ 6 16 36  7 40]


## Wymiary tablic

Tworzymy tablicę numpy.

In [227]:
array = np.array([
    [1, 2, 3, 5, 6],
    [2, 1, 5, 6, 7]
])
print(array)

[[1 2 3 5 6]
 [2 1 5 6 7]]


Ilość wymiarów tablicy:

In [228]:
print(array.ndim)

2


Kształt tablicy:

In [229]:
print(array.shape)

(2, 5)


Rozmiar tablicy:

In [230]:
print(array.size)

10


## Szukanie maksimum

Tworzymy tablicę 5x4 wypełnioną wartościami od 0 do 19.

In [231]:
array = np.arange(20).reshape(5, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Szukamy indeksu maksimum w tablicy. Domyślnie znajdujemy indeks maksimum w całej tablicy.

In [232]:
print(np.argmax(array))

19


Jeżeli podamy parametr axis=1, to znajdziemy indeks maksimum dla każdego wiersza.

In [233]:
print(np.argmax(array, axis=1))

[3 3 3 3 3]


Jeżeli podamy parametr axis=1, to znajdziemy indeks maksimum dla każdej kolumny.

In [234]:
print(np.argmax(array, axis=0))

[4 4 4 4]


## Sortowanie

Tworzymy przykładową tablicę

In [235]:
array = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])
print(array)

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]


Sortujemy całą tablicę.

In [236]:
print(np.sort(array, axis=None))

[ 1  2  3  3  5  6  7  7 10]


Sortujemy wiersze.

In [237]:
print(np.sort(array, axis=1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


Sortujemy kolumny.

In [238]:
print(np.sort(array, axis=0))

[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


## Obliczamy średnią

Tworzymy listę tablic numpy.

In [239]:
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

Dla każdej tablicy obliczamy średnią.

In [240]:
result = []
for i in range(len(list)):
    result.append(np.mean(list[i]))
print(result)

[5.5, 30.6, 34.0]


## Dodawanie wierzy i kolumn

Tworzymy przykładową tablicę numpy.

In [241]:
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])
print(array)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]]


Tworzymy nowy wiersz.

In [242]:
newRow = np.array([2, 1, 8])
print(newRow)

[2 1 8]


Tworzymy nową tablicę z dodanym wierszem.

In [243]:
newArray = np.vstack((array, newRow))
print(newArray)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


Tworzymy nową kolumnę.

In [244]:
newColumn = np.array([2, 1, 8])
print(newColumn)

[2 1 8]


Tworzymy nową tablicę z dodaną kolumną.

In [245]:
newArray = np.column_stack((array, newColumn))
print(newArray)

[[ 3  2  8  2]
 [ 4 12 34  1]
 [23 12 67  8]]


## Odwracanie tablicy

Tworzymy nową tablicę numpy.

In [246]:
array = np.array([3, 6, 7, 2, 5, 1, 8])

Tworzymy odwróconą tablicę.

In [247]:
reversedArray = np.flipud(array)
print(reversedArray)

[8 1 5 2 7 6 3]


## Mnożenie macierzy

Tworzymy macierze.

In [248]:
matrix1 = np.array([
    [3, 4, 2],
    [5, 1, 8],
    [3, 1, 9]
])
print(matrix1)

[[3 4 2]
 [5 1 8]
 [3 1 9]]


In [249]:
matrix2 = np.array([
    [3, 7, 5],
    [2, 9, 8],
    [1, 5, 8]
])
print(matrix2)

[[3 7 5]
 [2 9 8]
 [1 5 8]]


Obliczamy ich iloczyn.

In [250]:
result = np.dot(matrix1, matrix2)
print(result)

[[19 67 63]
 [25 84 97]
 [20 75 95]]


## Wzór szachownicy

Definiujemy rozmiar szachownicy.

In [251]:
n = 8

Tworzymy macierz n x n wypełnioną zerami.

In [252]:
matrix = np.zeros((n, n), dtype=int)

Wypełniamy jedynkami naprzemienne wiersze i kolumny

In [253]:
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Operacje na macierzach

Tworzmy macierz.

In [254]:
array = np.array([
    [6, 1, 1],
    [4, -2, 5],
    [2, 8, 7]
])

Wyznacznik macierzy.

In [255]:
determinant = np.linalg.det(array)
print(determinant)

-306.0


Transpozycja macierzy.

In [256]:
transpose = np.transpose(array)
print(transpose)

[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


Macierz odwrotna.

In [257]:
inverse = np.linalg.inv(array)
print(inverse)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


## Równania liniowe

In [258]:
A = np.array([
    [1, 3],
    [2, 4]
])

b = np.array([
    [7],
    [10]
])

x = np.linalg.solve(A, b)
print(x)

[[1.]
 [2.]]
